### ISSUE TITLE
agent.eval() 中'SPDiff' object has no attribute 'hyperparams'

### ISSUE THREAD

**Issue by ziyingTan** [tsinghua-fib-lab/SPDiff#4]
您好，请问在进行模型评估时SPDiff的hyperparams应用如何设置，我没有在代码或者配置文件中找到hyperparams的具体内容

**Comment by JoeSandos** [comment]
您好，不好意思，这一部分是遗留的实验代码。请您查看我们此次的更新

**Comment by ziyingTan** [comment]
我已经看到啦，非常感谢您的回复和更新！

**Comment by JoeSandos** [comment]
I'm going to close this issue, but please feel free to start new one if you need any other help!
